
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        CUSTOMER_ADD_NEW : "CUSTOMER_ADD_NEW",
        CUSTOMER_CATEGORY_ADD_NEW : "CUSTOMER_CATEGORY_ADD_NEW",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        CUSTOMER_DELETE: "CUSTOMER_DELETE",
        CUSTOMER_CATEGORY_DELETE: "CUSTOMER_CATEGORY_DELETE"
    },
});
